# Generated by Django 4.1.7 on 2023-03-25 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 19, 55, 2, 806616)),
        ),
    ]
