# Generated by Django 4.1.7 on 2023-03-25 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_user_password'),
        ('post', '0002_alter_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 19, 57, 34, 129049)),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user'),
        ),
    ]
