# Generated by Django 4.1.7 on 2023-03-25 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
