# Generated by Django 4.1.7 on 2023-03-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_interaction',
            name='date_comment',
        ),
    ]
