# Generated by Django 4.1.7 on 2023-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_interaction_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hide_like',
            field=models.BooleanField(default=False),
        ),
    ]
