# Generated by Django 4.1.7 on 2023-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_hide_comment_post_hide_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='all', max_length=20),
        ),
    ]
