# Generated by Django 4.1.7 on 2023-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
