# Generated by Django 4.1.7 on 2023-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45, unique=True)),
                ('name_lastname', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=65)),
                ('bio', models.CharField(default='', max_length=300)),
                ('avatar', models.BooleanField(default=False)),
                ('verificated', models.BooleanField(default=False)),
                ('online', models.CharField(default='1', max_length=10)),
            ],
        ),
    ]
