# Generated by Django 4.1.7 on 2023-04-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=300)),
                ('avatar_small', models.ImageField(blank=True, upload_to='static/img/small/avatar')),
                ('avatar_medium', models.ImageField(blank=True, upload_to='static/img/medium/avatar')),
                ('avatar_big', models.ImageField(blank=True, upload_to='static/img/big/avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
            options={
                'db_table': 'userProfile',
            },
        ),
    ]
