# Generated by Django 4.1.7 on 2023-04-20 13:30

from django.db import migrations, models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='confirmation_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_big',
            field=models.ImageField(blank=True, upload_to=signup.models.upload_big_avatar),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_medium',
            field=models.ImageField(blank=True, upload_to=signup.models.upload_medium_avatar),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small',
            field=models.ImageField(blank=True, upload_to=signup.models.upload_small_avatar),
        ),
    ]
