# Generated by Django 4.1.7 on 2023-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_token_confirmation_key_alter_userprofile_avatar_big_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
