# Generated by Django 4.1.7 on 2023-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_alter_token_confirmation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
