# Generated by Django 4.1.7 on 2023-04-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_alter_token_confirmation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_medium',
        ),
    ]
