# Generated by Django 4.1.7 on 2023-05-06 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_remove_userprofile_avatar_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
