# Generated by Django 4.1.7 on 2023-05-06 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
