# Generated by Django 4.1.7 on 2023-06-13 10:57

from django.db import migrations, models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_big',
            field=models.ImageField(default='static/img/big/avatar/standard.png', upload_to=signup.models.upload_big_avatar),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small',
            field=models.ImageField(default='static/img/small/avatar/standard.png', upload_to=signup.models.upload_small_avatar),
        ),
    ]
