# Generated by Django 4.1.7 on 2023-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_alter_userprofile_avatar_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_visibility',
            field=models.CharField(default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(default='all', max_length=30),
        ),
    ]
