# Generated by Django 4.1.7 on 2023-06-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0018_remove_userprofile_message_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_visibility',
        ),
    ]
