# Generated by Django 4.1.7 on 2023-06-16 09:31

from django.db import migrations, models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0019_remove_user_profile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_big',
            field=models.ImageField(upload_to=signup.models.upload_big_avatar),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small',
            field=models.ImageField(upload_to=signup.models.upload_small_avatar),
        ),
    ]
