# Generated by Django 4.1.7 on 2023-05-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0015_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='signup.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
