# Generated by Django 4.1.7 on 2023-05-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_alter_token_token'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_close_friends', to='signup.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_close_friends', to='signup.user')),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
