# Generated by Django 4.1.7 on 2023-05-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_closefriend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='closefriend',
            table='close_friend',
        ),
    ]
