# Generated by Django 4.1.7 on 2023-06-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_alter_token_token'),
        ('user', '0004_blacklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
